import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { renderGrammar } from './grammar-template.mjs';
import {
  buildSqlFunctionCallPattern,
  buildSqlKeywordPattern,
  getSqlFunctionInventory,
  getSqlKeywordInventory
} from './sql-keywords.mjs';

const projectDirectory = join(dirname(fileURLToPath(import.meta.url)), '..');
const grammarPath = join(projectDirectory, 'syntaxes', 'php-sql-strings.tmLanguage.json');
const sqlFixturePath = join(projectDirectory, 'test', 'fixtures', 'sql.tmLanguage.json');

const sqlGrammar = JSON.parse(readFileSync(sqlFixturePath, 'utf8'));
if (typeof sqlGrammar.version !== 'string' || sqlGrammar.version.length === 0) {
  throw new Error('The SQL grammar fixture has no source URL');
}

const keywordInventory = getSqlKeywordInventory(sqlGrammar);
const keywordPattern = buildSqlKeywordPattern(keywordInventory.keywords);
const functionInventory = getSqlFunctionInventory(sqlGrammar);
const functionCallPattern = buildSqlFunctionCallPattern(functionInventory.functions);
const starterPattern = String.raw`(?:\([\t ]*)*(?:${keywordPattern}|${functionCallPattern})`;

const informationForContributors = [
  'SQL starter patterns are generated by scripts/build-grammar.mjs; do not edit them manually.',
  `SQL grammar source: ${sqlGrammar.version}.`,
  `Keyword inventory: ${keywordInventory.counts.broad} broad-rule, `
    + `${keywordInventory.counts.scoped} scoped-rule, `
    + `${keywordInventory.counts.vscode} unique from vscode-mssql, `
    + `${keywordInventory.counts.supplementalAdditions} supplemental additions, `
    + `${keywordInventory.counts.total} starters.`,
  `Function inventory: ${functionInventory.counts.ordinaryRules} ordinary rules, `
    + `${functionInventory.counts.rawAlternatives} alternatives, `
    + `${functionInventory.counts.expandedOccurrences} expanded occurrences, `
    + `${functionInventory.counts.total} unique call starters; excludes `
    + `${functionInventory.counts.excludedGlobalVariableRules} @@ global-variable rule.`
];

const expectedGrammarContents = renderGrammar({
  starterPattern,
  informationForContributors
});

if (process.argv.includes('--check')) {
  let currentGrammarContents;
  try {
    currentGrammarContents = readFileSync(grammarPath, 'utf8');
  } catch (error) {
    if (error.code !== 'ENOENT') {
      throw error;
    }
  }

  if (currentGrammarContents !== expectedGrammarContents) {
    const state = currentGrammarContents === undefined ? 'missing' : 'stale';
    console.error(`Generated grammar is ${state}: syntaxes/php-sql-strings.tmLanguage.json`);
    console.error('Run npm run build:grammar and commit the updated grammar.');
    process.exitCode = 1;
  } else {
    console.log(
      `Grammar starter patterns are current (${keywordInventory.keywords.length} keywords, `
        + `${functionInventory.functions.length} function calls)`
    );
  }
} else {
  writeFileSync(grammarPath, expectedGrammarContents);
  console.log(
    `Generated grammar with ${keywordInventory.keywords.length} SQL keyword starters and `
      + `${functionInventory.functions.length} SQL function-call starters`
  );
}
